  
#
# Copyright 2018 IBM All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

version: '2'

services:

  orderer.trade.com:
    container_name: orderer.trade.com
    image: hyperledger/fabric-orderer:$IMAGE_TAG
    environment:
      - ORDERER_GENERAL_LOGLEVEL=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=TradeOrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
    - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
    - ../crypto-config/ordererOrganizations/trade.com/orderers/orderer.trade.com/msp:/var/hyperledger/orderer/msp
    - ../crypto-config/ordererOrganizations/trade.com/orderers/orderer.trade.com/tls/:/var/hyperledger/orderer/tls
    - orderer.trade.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050

  peer0.seller0org.trade.com:
    container_name: peer0.seller0org.trade.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.seller0org.trade.com
      - CORE_PEER_ADDRESS=peer0.seller0org.trade.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.seller0org.trade.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.seller0org.trade.com:7051
      - CORE_PEER_LOCALMSPID=Seller0OrgMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/seller0org.trade.com/peers/peer0.seller0org.trade.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/seller0org.trade.com/peers/peer0.seller0org.trade.com/tls:/etc/hyperledger/fabric/tls
        - peer0.seller0org.trade.com:/var/hyperledger/production
    ports:
      - 7051:7051
      - 7053:7053
      - 7055:6060

  peer0.seller1org.trade.com:
    container_name: peer0.seller1org.trade.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.seller1org.trade.com
      - CORE_PEER_ADDRESS=peer0.seller1org.trade.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.seller1org.trade.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.seller1org.trade.com:7051
      - CORE_PEER_LOCALMSPID=Seller1OrgMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/seller1org.trade.com/peers/peer0.seller1org.trade.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/seller1org.trade.com/peers/peer0.seller1org.trade.com/tls:/etc/hyperledger/fabric/tls
        - peer0.seller1org.trade.com:/var/hyperledger/production
    ports:
      - 8051:7051
      - 8053:7053
      - 8055:6060

  peer0.buyer0org.trade.com:
    container_name: peer0.buyer0org.trade.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.buyer0org.trade.com
      - CORE_PEER_ADDRESS=peer0.buyer0org.trade.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.buyer0org.trade.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.buyer0org.trade.com:7051
      - CORE_PEER_LOCALMSPID=Buyer0OrgMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/buyer0org.trade.com/peers/peer0.buyer0org.trade.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/buyer0org.trade.com/peers/peer0.buyer0org.trade.com/tls:/etc/hyperledger/fabric/tls
        - peer0.buyer0org.trade.com:/var/hyperledger/production

    ports:
      - 9051:7051
      - 9053:7053
      - 9055:6060
  
  peer0.buyer1org.trade.com:
    container_name: peer0.buyer1org.trade.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.buyer1org.trade.com
      - CORE_PEER_ADDRESS=peer0.buyer1org.trade.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.buyer1org.trade.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.buyer1org.trade.com:7051
      - CORE_PEER_LOCALMSPID=Buyer1OrgMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/buyer1org.trade.com/peers/peer0.buyer1org.trade.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/buyer1org.trade.com/peers/peer0.buyer1org.trade.com/tls:/etc/hyperledger/fabric/tls
        - peer0.buyer1org.trade.com:/var/hyperledger/production

    ports:
      - 10051:7051
      - 10053:7053
      - 10055:6060

  peer0.carrierorg.trade.com:
    container_name: peer0.carrierorg.trade.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.carrierorg.trade.com
      - CORE_PEER_ADDRESS=peer0.carrierorg.trade.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.carrierorg.trade.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.carrierorg.trade.com:7051
      - CORE_PEER_LOCALMSPID=CarrierOrgMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/carrierorg.trade.com/peers/peer0.carrierorg.trade.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/carrierorg.trade.com/peers/peer0.carrierorg.trade.com/tls:/etc/hyperledger/fabric/tls
        - peer0.carrierorg.trade.com:/var/hyperledger/production
    ports:
      - 11051:7051
      - 11053:7053
      - 11055:6060

  peer0.middlemanorg.trade.com:
    container_name: peer0.middlemanorg.trade.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.middlemanorg.trade.com
      - CORE_PEER_ADDRESS=peer0.middlemanorg.trade.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.middlemanorg.trade.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.middlemanorg.trade.com:7051
      - CORE_PEER_LOCALMSPID=MiddlemanOrgMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/middlemanorg.trade.com/peers/peer0.middlemanorg.trade.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/middlemanorg.trade.com/peers/peer0.middlemanorg.trade.com/tls:/etc/hyperledger/fabric/tls
        - peer0.middlemanorg.trade.com:/var/hyperledger/production
    ports:
      - 12051:7051
      - 12053:7053
      - 12055:6060

  peer0.warehouseorg.trade.com:
    container_name: peer0.warehouseorg.trade.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.warehouseorg.trade.com
      - CORE_PEER_ADDRESS=peer0.warehouseorg.trade.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.warehouseorg.trade.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.warehouseorg.trade.com:7051
      - CORE_PEER_LOCALMSPID=WarehouseOrgMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/warehouseorg.trade.com/peers/peer0.warehouseorg.trade.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/warehouseorg.trade.com/peers/peer0.warehouseorg.trade.com/tls:/etc/hyperledger/fabric/tls
        - peer0.warehouseorg.trade.com:/var/hyperledger/production
    ports:
      - 13051:7051
      - 13053:7053
      - 13055:6060