#
# Copyright 2018 IBM All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

################################################################################
#
#   Section: Organizations
#
#   - This section defines the different organizational identities which will
#   be referenced later in the configuration.
#
################################################################################
Organizations:

    # SampleOrg defines an MSP using the sampleconfig.  It should never be used
    # in production but may be used as a template for other definitions
    - &TradeOrdererOrg
        # DefaultOrg defines the organization which is used in the sampleconfig
        # of the fabric.git development environment
        Name: TradeOrdererOrg

        # ID to load the MSP definition as
        ID: TradeOrdererMSP

        # MSPDir is the filesystem path which contains the MSP configuration
        MSPDir: crypto-config/ordererOrganizations/trade.com/msp

        # Policies for reading, writing, configuration
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('TradeOrdererMSP.member')"
            Writers:
                Type: Signature
                Rule: "OR('TradeOrdererMSP.member')"
            Admins:
                Type: Signature
                Rule: "OR('TradeOrdererMSP.admin')"

    - &Seller0Org
        # DefaultOrg defines the organization which is used in the sampleconfig
        # of the fabric.git development environment
        Name: Seller0OrgMSP

        # ID to load the MSP definition as
        ID: Seller0OrgMSP

        MSPDir: crypto-config/peerOrganizations/seller0org.trade.com/msp

        # Policies for reading, writing, configuration
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('Seller0OrgMSP.admin', 'Seller0OrgMSP.peer', 'Seller0OrgMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('Seller0OrgMSP.admin', 'Seller0OrgMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('Seller0OrgMSP.admin')"

        AnchorPeers:
            # AnchorPeers defines the location of peers which can be used
            # for cross org gossip communication.  Note, this value is only
            # encoded in the genesis block in the Application section context
            - Host: peer0.seller0org.trade.com
              Port: 7051

    - &Seller1Org
        # DefaultOrg defines the organization which is used in the sampleconfig
        # of the fabric.git development environment
        Name: Seller1OrgMSP

        # ID to load the MSP definition as
        ID: Seller1OrgMSP

        MSPDir: crypto-config/peerOrganizations/seller1org.trade.com/msp

        # Policies for reading, writing, configuration
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('Seller1OrgMSP.admin', 'Seller1OrgMSP.peer', 'Seller1OrgMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('Seller1OrgMSP.admin', 'Seller1OrgMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('Seller1OrgMSP.admin')"

        AnchorPeers:
            # AnchorPeers defines the location of peers which can be used
            # for cross org gossip communication.  Note, this value is only
            # encoded in the genesis block in the Application section context
            - Host: peer0.seller1org.trade.com
              Port: 7051

    - &Buyer0Org
        # DefaultOrg defines the organization which is used in the sampleconfig
        # of the fabric.git development environment
        Name: Buyer0OrgMSP

        # ID to load the MSP definition as
        ID: Buyer0OrgMSP

        MSPDir: crypto-config/peerOrganizations/buyer0org.trade.com/msp

        # Policies for reading, writing, configuration
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('Buyer0OrgMSP.admin', 'Buyer0OrgMSP.peer', 'Buyer0OrgMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('Buyer0OrgMSP.admin', 'Buyer0OrgMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('Buyer0OrgMSP.admin')"

        AnchorPeers:
            # AnchorPeers defines the location of peers which can be used
            # for cross org gossip communication.  Note, this value is only
            # encoded in the genesis block in the Application section context
            - Host: peer0.buyer0org.trade.com
              Port: 7051

    - &Buyer1Org
        # DefaultOrg defines the organization which is used in the sampleconfig
        # of the fabric.git development environment
        Name: Buyer1OrgMSP

        # ID to load the MSP definition as
        ID: Buyer1OrgMSP

        MSPDir: crypto-config/peerOrganizations/buyer1org.trade.com/msp

        # Policies for reading, writing, configuration
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('Buyer1OrgMSP.admin', 'Buyer1OrgMSP.peer', 'Buyer1OrgMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('Buyer1OrgMSP.admin', 'Buyer1OrgMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('Buyer1OrgMSP.admin')"

        AnchorPeers:
            # AnchorPeers defines the location of peers which can be used
            # for cross org gossip communication.  Note, this value is only
            # encoded in the genesis block in the Application section context
            - Host: peer0.buyer1org.trade.com
              Port: 7051

    - &CarrierOrg
        # DefaultOrg defines the organization which is used in the sampleconfig
        # of the fabric.git development environment
        Name: CarrierOrgMSP

        # ID to load the MSP definition as
        ID: CarrierOrgMSP

        MSPDir: crypto-config/peerOrganizations/carrierorg.trade.com/msp

        # Policies for reading, writing, configuration
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('CarrierOrgMSP.admin', 'CarrierOrgMSP.peer', 'CarrierOrgMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('CarrierOrgMSP.admin', 'CarrierOrgMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('CarrierOrgMSP.admin')"

        AnchorPeers:
            # AnchorPeers defines the location of peers which can be used
            # for cross org gossip communication.  Note, this value is only
            # encoded in the genesis block in the Application section context
            - Host: peer0.carrierorg.trade.com
              Port: 7051

    - &MiddlemanOrg
        # DefaultOrg defines the organization which is used in the sampleconfig
        # of the fabric.git development environment
        Name: MiddlemanOrgMSP

        # ID to load the MSP definition as
        ID: MiddlemanOrgMSP

        MSPDir: crypto-config/peerOrganizations/middlemanorg.trade.com/msp

        # Policies for reading, writing, configuration
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('MiddlemanOrgMSP.admin', 'MiddlemanOrgMSP.peer', 'MiddlemanOrgMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('MiddlemanOrgMSP.admin', 'MiddlemanOrgMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('MiddlemanOrgMSP.admin')"

        AnchorPeers:
            # AnchorPeers defines the location of peers which can be used
            # for cross org gossip communication.  Note, this value is only
            # encoded in the genesis block in the Application section context
            - Host: peer0.middlemanorg.trade.com
              Port: 7051

    - &WarehouseOrg
        # DefaultOrg defines the organization which is used in the sampleconfig
        # of the fabric.git development environment
        Name: WarehouseOrgMSP

        # ID to load the MSP definition as
        ID: WarehouseOrgMSP

        MSPDir: crypto-config/peerOrganizations/warehouseorg.trade.com/msp

        # Policies for reading, writing, configuration
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('WarehouseOrgMSP.admin', 'WarehouseOrgMSP.peer', 'WarehouseOrgMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('WarehouseOrgMSP.admin', 'WarehouseOrgMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('WarehouseOrgMSP.admin')"

        AnchorPeers:
            # AnchorPeers defines the location of peers which can be used
            # for cross org gossip communication.  Note, this value is only
            # encoded in the genesis block in the Application section context
            - Host: peer0.warehouseorg.trade.com
              Port: 7051

################################################################################
#
#   SECTION: Orderer
#
#   - This section defines the values to encode into a config transaction or
#   genesis block for orderer related parameters
#
################################################################################
Orderer: &OrdererDefaults

    # Orderer Type: The orderer implementation to start
    # Available types are "solo" and "kafka"
    OrdererType: solo

    Addresses:
        - orderer.trade.com:7050

    # Batch Timeout: The amount of time to wait before creating a batch
    BatchTimeout: 2s

    # Batch Size: Controls the number of messages batched into a block
    BatchSize:

        # Max Message Count: The maximum number of messages to permit in a batch
        MaxMessageCount: 10

        # Absolute Max Bytes: The absolute maximum number of bytes allowed for
        # the serialized messages in a batch.
        AbsoluteMaxBytes: 99 MB

        # Preferred Max Bytes: The preferred maximum number of bytes allowed for
        # the serialized messages in a batch. A message larger than the preferred
        # max bytes will result in a batch larger than preferred max bytes.
        PreferredMaxBytes: 512 KB

    Kafka:
        # Brokers: A list of Kafka brokers to which the orderer connects
        # NOTE: Use IP:port notation
        Brokers:
            - 127.0.0.1:9092

    # Organizations is the list of orgs which are defined as participants on
    # the orderer side of the network
    Organizations:

    # Policies defines the set of policies at this level of the config tree
    # For Orderer policies, their canonical path is
    #   /Channel/Orderer/<PolicyName>
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "ANY Admins"
        # BlockValidation specifies what signatures must be included in the block
        # from the orderer for the peer to validate it.
        BlockValidation:
            Type: ImplicitMeta
            Rule: "ANY Writers"

################################################################################
#
#   SECTION: Application
#
#   - This section defines the values to encode into a config transaction or
#   genesis block for application related parameters
#
################################################################################
Application: &ApplicationDefaults

    # Organizations is the list of orgs which are defined as participants on
    # the application side of the network
    Organizations:

    # Policies defines the set of policies at this level of the config tree
    # For Application policies, their canonical path is
    #   /Channel/Application/<PolicyName>
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "ANY Admins"

################################################################################
#
#   CHANNEL
#
#   This section defines the values to encode into a config transaction or
#   genesis block for channel related parameters.
#
################################################################################
Channel: &ChannelDefaults
    # Policies defines the set of policies at this level of the config tree
    # For Channel policies, their canonical path is
    #   /Channel/<PolicyName>
    Policies:
        # Who may invoke the 'Deliver' API
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        # Who may invoke the 'Broadcast' API
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        # By default, who may modify elements at this config level
        Admins:
            Type: ImplicitMeta
            Rule: "ANY Admins"

################################################################################
#
#   SECTION: Capabilities
#
#   - This section defines the capabilities of fabric network. This is a new
#   concept as of v1.1.0 and should not be utilized in mixed networks with
#   v1.0.x peers and orderers.  Capabilities define features which must be
#   present in a fabric binary for that binary to safely participate in the
#   fabric network.  For instance, if a new MSP type is added, newer binaries
#   might recognize and validate the signatures from this type, while older
#   binaries without this support would be unable to validate those
#   transactions.  This could lead to different versions of the fabric binaries
#   having different world states.  Instead, defining a capability for a channel
#   informs those binaries without this capability that they must cease
#   processing transactions until they have been upgraded.  For v1.0.x if any
#   capabilities are defined (including a map with all capabilities turned off)
#   then the v1.0.x peer will deliberately crash.
#
################################################################################
Capabilities:
    # Channel capabilities apply to both the orderers and the peers and must be
    # supported by both.  Set the value of the capability to true to require it.
    Global: &ChannelCapabilities
        # V1.1 for Global is a catchall flag for behavior which has been
        # determined to be desired for all orderers and peers running v1.0.x,
        # but the modification of which would cause incompatibilities.  Users
        # should leave this flag set to true.
        V1_4_3: true
        V1_1: false

    # Orderer capabilities apply only to the orderers, and may be safely
    # manipulated without concern for upgrading peers.  Set the value of the
    # capability to true to require it.
    Orderer: &OrdererCapabilities
        # V1.1 for Order is a catchall flag for behavior which has been
        # determined to be desired for all orderers running v1.0.x, but the
        # modification of which  would cause incompatibilities.  Users should
        # leave this flag set to true.
        V1_4_2: true
        V1_1: false

    # Application capabilities apply only to the peer network, and may be safely
    # manipulated without concern for upgrading orderers.  Set the value of the
    # capability to true to require it.
    Application: &ApplicationCapabilities
        # V1.1 for Application is a catchall flag for behavior which has been
        # determined to be desired for all peers running v1.0.x, but the
        # modification of which would cause incompatibilities.  Users should
        # leave this flag set to true.
        V1_4_2: true
        V1_2: false

################################################################################
#
#   Profile
#
#   - Different configuration profiles may be encoded here to be specified
#   as parameters to the configtxgen tool
#
################################################################################
Profiles:

    FourOrgsTradeOrdererGenesis:
        <<: *ChannelDefaults
        Capabilities:
            <<: *ChannelCapabilities
        Orderer:
            <<: *OrdererDefaults
            Organizations:
                - *TradeOrdererOrg
            Capabilities:
                <<: *OrdererCapabilities
        Consortiums:
            TradeConsortium:
                Organizations:
                    - *Seller0Org
                    - *Seller1Org
                    - *Buyer0Org
                    - *Buyer1Org
                    - *CarrierOrg
                    - *MiddlemanOrg
                    - *WarehouseOrg
    FourOrgsTradeChannel:
        Consortium: TradeConsortium
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *Seller0Org
                - *Seller1Org
                - *Buyer0Org
                - *Buyer1Org
                - *CarrierOrg
                - *MiddlemanOrg
                - *WarehouseOrg
            Capabilities:
                <<: *ApplicationCapabilities