#
# Copyright 2018 IBM All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

version: '2'

volumes:
  orderer.trade.com:
  peer0.seller0org.trade.com:
  peer0.seller1org.trade.com:
  peer0.buyer0org.trade.com:
  peer0.buyer1org.trade.com:
  peer0.carrierorg.trade.com:
  peer0.middlemanorg.trade.com:
  peer0.warehouseorg.trade.com:

networks:
  trade:
services:
  couchdb:
    container_name: couchdb0
    image: couchdb:2.3
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    ports:
      - "5984:5984"
    networks:
      - trade

  seller0-ca:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-seller0org
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.seller0org.trade.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/SELLER0_CA_PRIVATE_KEY
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.seller0org.trade.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/SELLER0_CA_PRIVATE_KEY -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/seller0org.trade.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerSeller0Org
    networks:
      - trade

  seller1-ca:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-seller1org
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.seller1org.trade.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/SELLER1_CA_PRIVATE_KEY
    ports:
      - "8054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.seller1org.trade.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/SELLER1_CA_PRIVATE_KEY -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/seller1org.trade.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerSeller1Org
    networks:
      - trade

  buyer0-ca:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-buyer0org
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.buyer0org.trade.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/BUYER0_CA_PRIVATE_KEY
    ports:
      - "9054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.buyer0org.trade.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/BUYER0_CA_PRIVATE_KEY -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/buyer0org.trade.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerBuyer0Org
    networks:
      - trade

  buyer1-ca:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-buyer1org
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.buyer1org.trade.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/BUYER1_CA_PRIVATE_KEY
    ports:
      - "10054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.buyer1org.trade.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/BUYER1_CA_PRIVATE_KEY -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/buyer1org.trade.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerBuyer1Org
    networks:
      - trade

  carrier-ca:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-carrierorg
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.carrierorg.trade.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/CARRIER_CA_PRIVATE_KEY
    ports:
      - "11054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.carrierorg.trade.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/CARRIER_CA_PRIVATE_KEY -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/carrierorg.trade.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerCarrierOrg
    networks:
      - trade

  middleman-ca:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-middlemanorg
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.middlemanorg.trade.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/MIDDLEMAN_CA_PRIVATE_KEY
    ports:
      - "12054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.middlemanorg.trade.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/MIDDLEMAN_CA_PRIVATE_KEY -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/middlemanorg.trade.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerMiddlemanOrg
    networks:
      - trade

  warehouse-ca:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-warehouseorg
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.warehouseorg.trade.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/WAREHOUSE_CA_PRIVATE_KEY
    ports:
      - "13054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.warehouseorg.trade.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/WAREHOUSE_CA_PRIVATE_KEY -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/warehouseorg.trade.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerWarehouseOrg
    networks:
      - trade

  orderer.trade.com:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.trade.com
    container_name: orderer.trade.com
    networks:
      - trade

  peer0.seller0org.trade.com:
    container_name: peer0.seller0org.trade.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.seller0org.trade.com
    networks:
      - trade

  peer0.seller1org.trade.com:
    container_name: peer0.seller1org.trade.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.seller1org.trade.com
    networks:
      - trade

  peer0.buyer0org.trade.com:
    container_name: peer0.buyer0org.trade.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.buyer0org.trade.com
    networks:
      - trade

  peer0.buyer1org.trade.com:
    container_name: peer0.buyer1org.trade.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.buyer1org.trade.com
    networks:
      - trade

  peer0.carrierorg.trade.com:
    container_name: peer0.carrierorg.trade.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.carrierorg.trade.com
    networks:
      - trade

  peer0.middlemanorg.trade.com:
    container_name: peer0.middlemanorg.trade.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.middlemanorg.trade.com
    networks:
      - trade
  
  peer0.warehouseorg.trade.com:
    container_name: peer0.warehouseorg.trade.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.warehouseorg.trade.com
    networks:
      - trade